ifeq ($(findstring 86, $(ProgramFiles)), )
	PROGFILES := C:/Program Files
else
	PROGFILES := C:/Program Files (x86)
endif

GNU_INSTALL_ROOT := D:/software/QMK_MSYS/mingw64
GNU_VERSION := 9.3.1
GNU_PREFIX := arm-none-eabi

